- name: setup backend for testing loadbalancer
  hosts: localhost
  become: yes
  vars:
    project_dir: "/home/ubuntu/backend"

  tasks:
    - name: Install GO
      apt:
        name: golang-go
        state: present
        
    - name: Install stress-ng on Debian/Ubuntu
      ansible.builtin.apt:
        name: stress-ng
        state: present
      when: ansible_facts['os_family'] == "Debian"
    
    - name: Initialize Go module and download dependencies
      shell: |
        cd /home/ubuntu/backend
        go mod download
        go mod tidy
      environment:
        GOPATH: /home/ubuntu/go
        GOMODCACHE: /home/ubuntu/go/pkg/mod

    - name: Start backend Go application
      command: /usr/bin/go run /home/ubuntu/backend/backend.go
      args:
        chdir: /home/ubuntu/backend
      environment:
        GOPATH: /home/ubuntu/go
        GOMODCACHE: /home/ubuntu/go/pkg/mod



